<a href="https://colab.research.google.com/github/namirachmi08/Text-Similarity/blob/main/Text%20Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Kelas 2025C

Nama Anggota Kelompok:

Namira Rachmi Andini (Nim 25031554153)

Syahira Nanda Raihanna (Nim 25031554199)

# Chapter 7 - Text Similarity

## Cosine Similarity

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi numerik dengan Count Vectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Menghitung cosine similarity
similarity = cosine_similarity(X)

print(similarity)

[[1.         0.0243975  0.         ... 0.03615508 0.01792443 0.06043979]
 [0.0243975  1.         0.         ... 0.09261982 0.0852757  0.05529674]
 [0.         0.         1.         ... 0.         0.00949105 0.00800077]
 ...
 [0.03615508 0.09261982 0.         ... 1.         0.09234842 0.02458356]
 [0.01792443 0.0852757  0.00949105 ... 0.09234842 1.         0.05687581]
 [0.06043979 0.05529674 0.00800077 ... 0.02458356 0.05687581 1.        ]]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi matriks TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Menghitung cosine similarity
similarity = cosine_similarity(X)

print(similarity)

[[1.         0.02114272 0.         ... 0.00878883 0.00601551 0.03179402]
 [0.02114272 1.         0.         ... 0.06578714 0.04970315 0.02587053]
 [0.         0.         1.         ... 0.         0.00836835 0.00699347]
 ...
 [0.00878883 0.06578714 0.         ... 1.         0.04490701 0.00745942]
 [0.00601551 0.04970315 0.00836835 ... 0.04490701 1.         0.02726146]
 [0.03179402 0.02587053 0.00699347 ... 0.00745942 0.02726146 1.        ]]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.spatial.distance import pdist

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi binary vector
vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()

print(X)

# Menghitung cosine similarity
similarity = 1 - pdist(X, metric='cosine')

print(similarity)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0.02807173 0.         0.02017425 ... 0.11826248 0.02193172 0.04992872]

## Jaccard

In [ ]:
# JACCARD
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import jaccard_score
from scipy.spatial.distance import pdist

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi binary vector
vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()

# Menghitung jarak Jaccard antar semua dokumen
distances = pdist(X, metric='jaccard')

print("Jaccard distance:")
print(distances[:10])

Jaccard distance:
[0.98630137 1.         0.99145299 0.98496241 0.98591549 0.97520661
 0.98076923 0.96946565 0.97687861 1.        ]

In [ ]:
# Similarity dokumen 1 dan 2
Sd1d2 = jaccard_score(X[0], X[1])

# Similarity dokumen 1 dan 3
Sd1d3 = jaccard_score(X[0], X[2])

# Similarity dokumen 2 dan 3
Sd2d3 = jaccard_score(X[1], X[2])

print("Similarity Doc 1 - Doc 2:", Sd1d2)
print("Similarity Doc 1 - Doc 3:", Sd1d3)
print("Similarity Doc 2 - Doc 3:", Sd2d3)

Similarity Doc 1 - Doc 2: 0.0136986301369863
Similarity Doc 1 - Doc 3: 0.0
Similarity Doc 2 - Doc 3: 0.0

In [ ]:
similarity = 1 - distances

print("Jaccard similarity:")
print(similarity[:10])

Jaccard similarity:
[0.01369863 0.         0.00854701 0.01503759 0.01408451 0.02479339
 0.01923077 0.03053435 0.02312139 0.        ]

## Data Real

data: https://drive.google.com/file/d/1AIvJl72GQJnll4Z_AI1MEMVvlJkpke02/view?usp=sharing

In [ ]:
!pip install contractions

import numpy as np
import pandas as pd

from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

import sklearn
import nltk

nltk.download('stopwords')

from IPython.display import display, HTML

data = pd.read_csv("/content/drive/MyDrive/combined_data.csv", header='infer')

print("Total rows : ", len(data))

display(HTML(data.head().to_html()))

Requirement already satisfied: contractions in /usr/local/lib/python3.13/dist-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in /usr/local/lib/python3.13/dist-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in /usr/local/lib/python3.13/dist-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.13/dist-packages (from textsearch>=0.0.21->contractions) (2.3.1)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Total rows :  97013

In [ ]:
print(data.columns.tolist())

['Unnamed: 0', 'genre', 'category', 'title', 'year', 'distribution', 'description', 'url', 'cover_photo']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

corpus = []

for description in data["description"].fillna("").to_list():
    tokens = description.lower().split()

    # Stemming dan stop-word removal
    tokens = [
        stemmer.stem(token)
        for token in tokens
        if token not in stop_words
    ]

    corpus.append(" ".join(tokens))

print(corpus[0])

literatur student anastasia steele' life chang forev meet handsome, yet tormented, billionair christian grey.

In [ ]:
# Membuat TF-IDF index berdasarkan seluruh corpus
vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    max_features=5000)

vectorizer.fit_transform(corpus)
print("Total features:", vectorizer.get_feature_names_out().shape)
vectorizer.get_feature_names_out()[:1000]

Total features: (5000,)

array(['000', '10', '100', '11', '11th', '12', '13', '13th', '14', '15',
       '16', '17', '18', '18th', '19', '1920', '1930', '1930s', '1940',
       '1941', '1942', '1944', '1945', '1950', '1950s', '1955', '1960',
       '1960s', '1962', '1968', '1969', '1970', '1970s', '1971', '1972',
       '1973', '1974', '1976', '1978', '1980', '1980s', '1984', '1985',
       '1987', '1990', '1999', '19th', '20', '200', '2000', '2002',
       '2003', '2008', '2010', '2011', '2013', '2016', '2017', '2018',
       '2019', '2020', '20th', '21', '21st', '22', '23', '24', '25', '26',
       '30', '300', '40', '400', '4th', '50', '500', '60', '70', '80',
       '90', 'aaron', 'abandon', 'abandoned', 'abbi', 'abduct',
       'abduction', 'abil', 'abl', 'aboard', 'abort', 'about', 'abraham',
       'abroad', 'absolut', 'abus', 'academ', 'academi', 'academy',
       'accept', 'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'accord', 'account', 'accus', 'ace', 'achiev',
       'acquaint', 'acquir', 'across', 'act', 'action', 'activ',
       'activist', 'activities', 'actor', 'actress', 'actual', 'ad',
       'adam', 'adapt', 'add', 'addict', 'addiction', 'addit', 'address',
       'aditya', 'adjust', 'admir', 'admit', 'adolesc', 'adolf', 'adopt',
       'ador', 'adult', 'adultery', 'adulthood', 'advanc', 'advantag',
       'adventur', 'adventure', 'adventures', 'advertis', 'advic',
       'advis', 'advoc', 'affair', 'affect', 'affluent', 'afford',
       'afghanistan', 'afoul', 'afraid', 'africa', 'african', 'after',
       'aftermath', 'ag', 'again', 'age', 'agenc', 'agency', 'agenda',
       'agent', 'agents', 'aggress', 'ago', 'agre', 'ahead', 'aid', 'ail',
       'aim', 'air', 'aircraft', 'airlin', 'airplan', 'airplane',
       'airport', 'ajay', 'aka', 'akash', 'akshay', 'al', 'alabama',
       'alan', 'alaska', 'albert', 'album', 'alcohol', 'alcoholism',
       'alex', 'alexand', 'alfr', 'ali', 'alia', 'alic', 'alice', 'alien',
       'aliens', 'alik', 'alike', 'aliv', 'alive', 'all', 'allan',
       'alleg', 'allen', 'alli', 'allianc', 'allison', 'allow', 'almost',
       'alon', 'alone', 'along', 'alongsid', 'alpha', 'alreadi', 'also',
       'altar', 'alter', 'altern', 'although', 'alway', 'aman', 'amanda',
       'amar', 'amateur', 'amaz', 'amazon', 'ambassador', 'amber',
       'ambit', 'ambiti', 'ambush', 'america', 'american', 'ami', 'amid',
       'amidst', 'amit', 'amitabh', 'amnesia', 'among', 'amongst', 'amor',
       'amount', 'amus', 'an', 'analyst', 'anand', 'ancestor', 'ancestr',
       'ancient', 'and', 'anderson', 'andi', 'andr', 'andrew', 'android',
       'andy', 'angel', 'angela', 'angeles', 'anger', 'angri', 'anim',
       'animal', 'animals', 'animation', 'anita', 'anjali', 'ann', 'anna',
       'anni', 'anniversari', 'announc', 'annual', 'anonym', 'anonymous',
       'anonymoustag', 'anoth', 'another', 'answer', 'antholog',
       'anthoni', 'anti', 'anticip', 'antiqu', 'anxiou', 'anymore',
       'anyon', 'anyone', 'anyth', 'anything', 'apach', 'apart',
       'apartment', 'ape', 'apocalyps', 'apocalypse', 'apocalypt',
       'apollo', 'app', 'appar', 'appear', 'appoint', 'apprehend',
       'apprentic', 'approach', 'approv', 'april', 'arab', 'arcad',
       'arch', 'archaeologist', 'archer', 'architect', 'archiv', 'arctic',
       'are', 'area', 'aris', 'aristocrat', 'arizona', 'arjun', 'arm',
       'armi', 'armor', 'armstrong', 'army', 'arnold', 'around', 'arrang',
       'arrest', 'arrested', 'arriv', 'arrival', 'arrive', 'arrives',
       'arrog', 'art', 'arthur', 'artifact', 'artifici', 'artist',
       'artists', 'arts', 'arun', 'as', 'ash', 'asha', 'ashley', 'ashok',
       'asia', 'asian', 'asid', 'ask', 'aspect', 'aspir', 'assassin',
       'assassination', 'assassins', 'assault', 'assembl', 'assign',
       'assignment', 'assist', 'assistant', 'associ', 'assort', 'assum',
       'astronaut', 'asylum', 'at', 'athlet', 'atlant', 'atlanta',
       'atmospher', 'atom', 'attach', 'attack', 'attacks', 'attempt',
       'attend', 'attent', 'attention', 'attic', 'attitud', 'attorney',
       'attract', 'audienc', 'audit', 'august', 'aunt', 'austin',
       'australia', 'australian', 'austrian', 'author', 'authorities',
       'autism', 'autist', 'auto', 'aveng', 'averag', 'avoid', 'await',
       'awak', 'awaken', 'awar', 'award', 'away', 'awkward', 'awri',
       'awry', 'baba', 'babi', 'baby', 'bachchan', 'bachelor', 'back',
       'backdrop', 'background', 'backwood', 'backyard', 'bad', 'badli',
       'bag', 'bail', 'baker', 'balanc', 'ball', 'ballerina', 'ballet',
       'ban', 'band', 'bandit', 'bangkok', 'banish', 'bank', 'banker',
       'bankrupt', 'bar', 'barbara', 'barber', 'bare', 'bargain', 'baron',
       'barri', 'bartend', 'bas', 'base', 'basebal', 'baseball',
       'basement', 'basketbal', 'basketball', 'bat', 'batman', 'battl',
       'battle', 'battlefield', 'baxter', 'bay', 'be', 'beach', 'bean',
       'bear', 'beast', 'beat', 'beaten', 'beauti', 'beautiful', 'beauty',
       'beavertag', 'becam', 'becom', 'bed', 'bedroom', 'been', 'beer',
       'before', 'befriend', 'began', 'begin', 'beginning', 'begins',
       'begun', 'behavior', 'behind', 'being', 'belief', 'believ', 'bell',
       'belong', 'belov', 'belt', 'ben', 'bend', 'beneath', 'benefit',
       'benjamin', 'bennett', 'bent', 'berlin', 'bernard', 'berni',
       'best', 'bestsel', 'bet', 'beth', 'betray', 'betrayal', 'better',
       'beverli', 'beyond', 'bhanu', 'biblic', 'bicycl', 'bid', 'big',
       'bigfoot', 'bigger', 'biggest', 'bike', 'biker', 'bikini', 'bill',
       'billi', 'billion', 'billionair', 'biograph', 'biographi',
       'biolog', 'biologist', 'biopic', 'bird', 'birth', 'birthday',
       'bishop', 'bit', 'bite', 'bitten', 'bitter', 'bizarr', 'black',
       'blackmail', 'blade', 'blair', 'blake', 'blame', 'blast', 'blend',
       'bless', 'blind', 'bliss', 'block', 'blond', 'blonde', 'blood',
       'bloodi', 'bloodthirsti', 'bloom', 'blossom', 'blow', 'blue',
       'blur', 'bo', 'board', 'boat', 'bob', 'bobbi', 'bobby', 'bodi',
       'bodies', 'body', 'bodyguard', 'boil', 'bold', 'bollywood', 'bomb',
       'bombay', 'bomber', 'bond', 'bone', 'bonni', 'book', 'books',
       'boost', 'boot', 'border', 'bore', 'born', 'borrow', 'boss',
       'boston', 'botch', 'both', 'bottl', 'bottom', 'bought', 'bound',
       'bounti', 'bowl', 'box', 'boxer', 'boxing', 'boy', 'boyfriend',
       'boys', 'brad', 'bradi', 'brain', 'brand', 'brandon', 'brash',
       'brave', 'break', 'breakdown', 'breakfast', 'breakthrough',
       'breakup', 'breath', 'breed', 'brenda', 'brian', 'bribe', 'bride',
       'bridg', 'brief', 'brien', 'bright', 'brilliant', 'bring', 'brink',
       'britain', 'british', 'broadcast', 'broadway', 'broke', 'broken',
       'broker', 'bronx', 'brook', 'brooklyn', 'brothel', 'brother',
       'brotherhood', 'brothers', 'brought', 'brown', 'bruce', 'brutal',
       'bu', 'buck', 'bud', 'buddi', 'budget', 'bug', 'build', 'building',
       'built', 'bull', 'bullet', 'bulli', 'bully', 'bumbl', 'bump',
       'bunch', 'bunker', 'bunni', 'burden', 'bureau', 'burglar', 'buri',
       'burn', 'burt', 'bus', 'bush', 'busi', 'business', 'businessman',
       'bust', 'but', 'butler', 'buy', 'buzz', 'by', 'bytag', 'cab',
       'cabin', 'caesar', 'cage', 'cal', 'california', 'call', 'calvin',
       'came', 'camera', 'camp', 'campaign', 'camper', 'campu', 'can',
       'canada', 'canadian', 'canal', 'cancel', 'cancer', 'candid',
       'cannib', 'cannot', 'capabl', 'capit', 'capt', 'captain', 'captiv',
       'captor', 'captur', 'captured', 'car', 'card', 'care', 'career',
       'carefre', 'cargo', 'caribbean', 'carl', 'carla', 'carlo',
       'carniv', 'carnival', 'carol', 'carolina', 'carri', 'cartel',
       'carter', 'cartoon', 'case', 'casey', 'cash', 'casino', 'cast',
       'castl', 'castle', 'cat', 'catastroph', 'catch', 'catherin',
       'cathol', 'cattl', 'caucasian', 'caught', 'caus', 'cavalri',
       'cave', 'celebr', 'cell', 'center', 'centr', 'central', 'centuri',
       'century', 'ceo', 'certain', 'cgi', 'chad', 'chagrin', 'chain',
       'chair', 'challeng', 'chamber', 'champ', 'champagn', 'champagne',
       'champion', 'championship', 'chan', 'chanc', 'chance', 'chang',
       'change', 'changed', 'channel', 'chao', 'chaos', 'chaotic',
       'chapter', 'charact', 'character', 'characters', 'charg', 'charge',
       'charismat', 'chariti', 'charl', 'charli', 'charlie', 'charlott',
       'charm', 'charming', 'chart', 'chase', 'chauffeur', 'cheap',
       'cheat', 'check', 'cheer', 'cheerlead', 'chef', 'chemic', 'chess',
       'chest', 'chicago', 'chicken', 'chief', 'child', 'childhood',
       'children', 'chill', 'china', 'chines', 'chinese', 'chip', 'chloe',
       'choic', 'choice', 'choir', 'choos', 'chopra', 'chosen', 'chow',
       'chri', 'chris', 'christ', 'christian', 'christma', 'christmas',
       'christoph', 'chronicl', 'chuck', 'church', 'cia', 'cigar',
       'cinderella', 'cinema', 'cinemat', 'circa', 'circl', 'circu',
       'circuit', 'circumst', 'circumstances', 'circus', 'citi',
       'citizen', 'citizens', 'city', 'civil', 'civilian', 'civilization',
       'clad', 'claim', 'clair', 'clan', 'clark', 'clash', 'class',
       'classic', 'classmat', 'classmate', 'clau', 'claud', 'claus',
       'clay', 'clean', 'clear', 'clerk', 'clever', 'client', 'clients',
       'cliff', 'climb', 'climber', 'clinic', 'clock', 'clone', 'close',
       'closer', 'closest', 'cloth', 'cloud', 'clown', 'club', 'clue',
       'clutch', 'co', 'coach', 'coal', 'coast', 'coastal', 'cobb',
       'cobra', 'cocain', 'code', 'codi', 'coffe', 'col', 'cold', 'cole',
       'colin', 'collabor', 'collaps', 'collar', 'colleagu', 'collect',
       'collector', 'colleg', 'college', 'collid', 'collin', 'collis',
       'colonel', 'coloni', 'color', 'colorado', 'com', 'coma', 'combat',
       'combin', 'come', 'comeback', 'comed', 'comedi', 'comedian',
       'comedy', 'comfort', 'comic', 'comics', 'coming', 'command',
       'commando', 'commerci', 'commiss', 'commission', 'commit',
       'common', 'commun', 'communist', 'community', 'compani',
       'companion', 'company', 'compassion', 'compel', 'compet',
       'competit', 'competition', 'competitor', 'complet', 'complex',
       'complic', 'complicated', 'compos', 'compound', 'compromis',
       'comput', 'computer', 'con', 'conceal', 'conceiv', 'concentr',
       'concern', 'concert', 'condemn', 'condit', 'conduct', 'conductor',
       'confeder', 'confess', 'confid', 'confin', 'conflict', 'confront',
       'confus', 'conjur', 'connect', 'connecticut', 'connection',
       'connor', 'conquer', 'consequ', 'consequences', 'conserv',
       'consid', 'consist'], dtype=object)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

documents_tfidf_features = vectorizer.transform(corpus)

TopK = 10

# Query pencarian film
query = "a young man who discovers a mysterious secret"

# Mengubah query menjadi TF-IDF vector
query_tfidf_features = vectorizer.transform([query])

print("TF-IDF features for query", query_tfidf_features, "\n")

# Menghitung cosine similarity
similarities = cosine_similarity(
    documents_tfidf_features,
    query_tfidf_features
)

# Mengambil 10 dokumen dengan similarity tertinggi
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
descriptions = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    descriptions.append(
        str(data.iloc[doc_index]["description"]).replace("\n", " ")
    )
    similarity_scores.append(similarities[doc_index, 0])

results = pd.DataFrame({
    "Title": titles,
    "Description": descriptions,
    "Similarities": similarity_scores
})

display(HTML(results.to_html()))

TF-IDF features for query <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (1, 5000)>
  Coords	Values
  (0, 2763)	0.30097858546349965
  (0, 3001)	0.6868732631713422
  (0, 3930)	0.3881861437012133
  (0, 4893)	0.4558089073009107
  (0, 4986)	0.28136589931310707

In [ ]:
# Jaccard
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

corpus = []

for description in data["description"].fillna("").to_list():
    tokens = description.lower().split()

    tokens = [
        stemmer.stem(token)
        for token in tokens
        if token not in stop_words
    ]

    corpus.append(" ".join(tokens))

print(corpus[0])

literatur student anastasia steele' life chang forev meet handsome, yet tormented, billionair christian grey.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    binary=True,
    max_features=5000)

documents_binarized_features = vectorizer.fit_transform(corpus).toarray()

print("Total features:", vectorizer.get_feature_names_out().shape)

vectorizer.get_feature_names_out()[:1000]

Total features: (5000,)

array(['000', '10', '100', '1000', '11', '11th', '12', '13', '13th', '14',
       '15', '16', '17', '18', '18th', '19', '1920', '1930', '1930s',
       '1940', '1941', '1942', '1944', '1945', '1950', '1950s', '1955',
       '1960', '1960s', '1962', '1966', '1968', '1969', '1970', '1970s',
       '1971', '1972', '1973', '1974', '1976', '1978', '1980', '1980s',
       '1984', '1985', '1987', '1990', '1993', '1999', '19th', '20',
       '200', '2000', '2002', '2003', '2008', '2010', '2011', '2013',
       '2016', '2017', '2018', '2019', '2020', '20th', '21', '21st', '22',
       '23', '24', '25', '26', '30', '300', '40', '400', '4th', '50',
       '500', '60', '70', '80', '90', 'aaron', 'abandon', 'abandoned',
       'abbi', 'abduct', 'abduction', 'abil', 'abilities', 'abl',
       'aboard', 'aborigin', 'abort', 'about', 'abraham', 'abroad',
       'absolut', 'abus', 'academ', 'academi', 'academy', 'accept',
       'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'accord', 'account', 'accus', 'ace', 'achiev',
       'acquaint', 'acquir', 'across', 'act', 'action', 'activ',
       'activist', 'activities', 'actor', 'actress', 'actual', 'ad',
       'adam', 'adapt', 'add', 'addict', 'addiction', 'addit', 'address',
       'adjust', 'admir', 'admit', 'adolesc', 'adolf', 'adopt', 'ador',
       'adult', 'adultery', 'adulthood', 'advanc', 'advantag', 'adventur',
       'adventure', 'adventures', 'advertis', 'advic', 'advis', 'advoc',
       'affair', 'affect', 'affluent', 'afford', 'afghanistan', 'afoul',
       'afraid', 'africa', 'african', 'after', 'aftermath', 'ag', 'again',
       'age', 'agenc', 'agency', 'agenda', 'agent', 'agents', 'aggress',
       'ago', 'agre', 'ahead', 'aid', 'ail', 'aim', 'air', 'aircraft',
       'airlin', 'airplan', 'airplane', 'airport', 'ajay', 'aka',
       'akshay', 'al', 'alabama', 'alan', 'alaska', 'albert', 'album',
       'alcohol', 'alcoholism', 'alex', 'alexand', 'alfr', 'ali', 'alia',
       'alic', 'alice', 'alien', 'aliens', 'alik', 'alike', 'aliv',
       'alive', 'all', 'allan', 'alleg', 'allegedli', 'allen', 'alli',
       'allianc', 'allow', 'almost', 'alon', 'alone', 'along', 'alongsid',
       'alpha', 'alreadi', 'also', 'alt', 'altar', 'alter', 'altern',
       'although', 'alway', 'aman', 'amanda', 'amar', 'amateur', 'amaz',
       'amazon', 'ambassador', 'ambit', 'ambiti', 'ambush', 'america',
       'american', 'ami', 'amid', 'amidst', 'amitabh', 'amnesia', 'among',
       'amongst', 'amor', 'amount', 'amus', 'an', 'anand', 'ancestor',
       'ancestr', 'ancient', 'and', 'anderson', 'andi', 'andr', 'andrew',
       'android', 'angel', 'angela', 'angeles', 'anger', 'angri', 'anim',
       'animal', 'animals', 'animation', 'anita', 'ann', 'anna', 'anni',
       'anniversari', 'announc', 'annual', 'anonym', 'anonymous',
       'anonymoustag', 'anoth', 'another', 'answer', 'antholog',
       'anthology', 'anthoni', 'anti', 'anticip', 'antiqu', 'anxiou',
       'anymore', 'anyon', 'anyone', 'anyth', 'anything', 'apach',
       'apart', 'apartment', 'ape', 'apocalyps', 'apocalypse',
       'apocalypt', 'apollo', 'app', 'appar', 'appear', 'appoint',
       'apprehend', 'apprentic', 'approach', 'approv', 'april', 'arab',
       'arch', 'archaeologist', 'architect', 'archiv', 'arctic', 'are',
       'area', 'argument', 'aris', 'aristocrat', 'arizona', 'arjun',
       'arm', 'armi', 'armor', 'armstrong', 'army', 'around', 'arrang',
       'arrest', 'arrested', 'arriv', 'arrival', 'arrive', 'arrives',
       'arrog', 'art', 'arthur', 'artifact', 'artifici', 'artist',
       'artists', 'arts', 'arun', 'as', 'ash', 'asha', 'ashley', 'ashok',
       'ashor', 'asia', 'asian', 'asid', 'ask', 'aspect', 'aspir',
       'assassin', 'assassination', 'assassins', 'assault', 'assembl',
       'assign', 'assignment', 'assist', 'assistant', 'associ', 'assort',
       'assum', 'astronaut', 'asylum', 'at', 'athlet', 'atlant',
       'atlanta', 'atmospher', 'atom', 'attach', 'attack', 'attacks',
       'attempt', 'attend', 'attent', 'attention', 'attitud', 'attorney',
       'attract', 'audienc', 'audit', 'august', 'aunt', 'austin',
       'australia', 'australian', 'austrian', 'author', 'authorities',
       'autism', 'autist', 'auto', 'aveng', 'averag', 'avoid', 'await',
       'awak', 'awaken', 'awar', 'award', 'away', 'awkward', 'awri',
       'awry', 'babi', 'baby', 'bachchan', 'bachelor', 'back', 'backdrop',
       'background', 'backwood', 'backyard', 'bad', 'badli', 'bag',
       'bail', 'baker', 'balanc', 'ball', 'ballerina', 'ballet', 'ban',
       'band', 'bandit', 'bangkok', 'banish', 'bank', 'banker',
       'bankrupt', 'bar', 'barbara', 'barber', 'bare', 'bargain', 'barn',
       'baron', 'barri', 'bartend', 'bas', 'base', 'basebal', 'baseball',
       'basement', 'basketbal', 'basketball', 'bat', 'batman', 'battl',
       'battle', 'battlefield', 'baxter', 'bay', 'be', 'beach', 'bear',
       'beast', 'beat', 'beaten', 'beauti', 'beautiful', 'beauty',
       'beavertag', 'becam', 'becom', 'bed', 'bedroom', 'been', 'beer',
       'before', 'befriend', 'began', 'begin', 'beginning', 'begins',
       'begun', 'behavior', 'behind', 'being', 'belief', 'believ', 'bell',
       'belong', 'belov', 'belt', 'ben', 'bend', 'beneath', 'benefit',
       'benjamin', 'bennett', 'bent', 'berlin', 'bernard', 'best',
       'bestsel', 'bet', 'beth', 'betray', 'betrayal', 'better',
       'beverli', 'beyond', 'biblic', 'bicycl', 'bicycle', 'bid', 'big',
       'bigfoot', 'bigger', 'biggest', 'bike', 'biker', 'bikini', 'bill',
       'billi', 'billion', 'billionair', 'biograph', 'biographi',
       'biolog', 'biologist', 'biopic', 'bird', 'birth', 'birthday',
       'bishop', 'bit', 'bite', 'bitten', 'bitter', 'bizarr', 'black',
       'blackmail', 'blade', 'blair', 'blake', 'blame', 'blast', 'blend',
       'bless', 'blind', 'bliss', 'block', 'blond', 'blonde', 'blood',
       'bloodi', 'bloodthirsti', 'bloom', 'blossom', 'blow', 'blue',
       'blur', 'bo', 'board', 'boat', 'bob', 'bobbi', 'bobby', 'bodi',
       'bodies', 'body', 'bodyguard', 'boil', 'bold', 'bollywood', 'bomb',
       'bombay', 'bomber', 'bond', 'bone', 'bonni', 'book', 'books',
       'boost', 'boot', 'border', 'bore', 'born', 'borrow', 'boss',
       'boston', 'botch', 'both', 'bottom', 'bought', 'bound', 'bounti',
       'bowl', 'box', 'boxer', 'boxing', 'boy', 'boyfriend', 'boys',
       'brad', 'bradi', 'brain', 'brand', 'brandon', 'brash', 'brave',
       'brazil', 'brazilian', 'break', 'breakdown', 'breakfast',
       'breakthrough', 'breakup', 'breath', 'breed', 'brian', 'bribe',
       'bride', 'bridg', 'brief', 'brien', 'bright', 'brilliant', 'bring',
       'brink', 'britain', 'british', 'broadcast', 'broadway', 'broke',
       'broken', 'broker', 'bronx', 'brook', 'brooklyn', 'brothel',
       'brother', 'brotherhood', 'brothers', 'brought', 'brown', 'bruce',
       'brutal', 'bu', 'buck', 'bud', 'buddi', 'budget', 'bug', 'build',
       'building', 'built', 'bull', 'bullet', 'bulli', 'bully', 'bumbl',
       'bump', 'bunch', 'bunker', 'bunni', 'burden', 'bureau', 'burglar',
       'buri', 'burn', 'burt', 'bus', 'bush', 'busi', 'business',
       'businessman', 'bust', 'but', 'butler', 'buy', 'buzz', 'by',
       'bytag', 'cab', 'cabin', 'cage', 'cal', 'california', 'call',
       'came', 'camera', 'camp', 'campaign', 'camper', 'campu', 'can',
       'canada', 'canadian', 'canal', 'cancel', 'cancer', 'candid',
       'canin', 'cannib', 'cannot', 'canyon', 'capabl', 'capit', 'capt',
       'captain', 'captiv', 'captor', 'captur', 'captured', 'car', 'card',
       'care', 'career', 'carefre', 'cargo', 'caribbean', 'carl', 'carla',
       'carlo', 'carniv', 'carnival', 'carol', 'carolina', 'carri',
       'cars', 'cartel', 'carter', 'cartoon', 'case', 'casey', 'cash',
       'casino', 'cast', 'castl', 'castle', 'cat', 'catastroph', 'catch',
       'cater', 'catherin', 'cathol', 'cattl', 'caucasian', 'caught',
       'caus', 'cavalri', 'cave', 'celebr', 'cell', 'center', 'centr',
       'central', 'centuri', 'centuries', 'century', 'ceo', 'certain',
       'cgi', 'chad', 'chagrin', 'chain', 'chair', 'challeng', 'chamber',
       'champ', 'champagn', 'champagne', 'champion', 'championship',
       'chan', 'chanc', 'chance', 'chang', 'change', 'changed', 'channel',
       'chao', 'chaos', 'chaotic', 'chapter', 'charact', 'character',
       'characters', 'charg', 'charge', 'charismat', 'chariti', 'charl',
       'charles', 'charli', 'charlie', 'charlott', 'charm', 'charming',
       'chart', 'chase', 'chauffeur', 'cheap', 'cheat', 'check', 'cheer',
       'cheerlead', 'chef', 'chemic', 'chess', 'chest', 'chicago',
       'chicken', 'chief', 'child', 'childhood', 'children', 'chill',
       'china', 'chines', 'chinese', 'chip', 'chloe', 'choic', 'choice',
       'choir', 'choos', 'chopra', 'chosen', 'chri', 'chris', 'christ',
       'christian', 'christma', 'christmas', 'christoph', 'chronicl',
       'chuck', 'church', 'cia', 'cigar', 'cinderella', 'cinema',
       'cinemat', 'circa', 'circl', 'circu', 'circuit', 'circumst',
       'circumstances', 'circus', 'citi', 'citizen', 'citizens', 'city',
       'civil', 'civilian', 'civilization', 'clad', 'claim', 'clair',
       'clan', 'clark', 'clash', 'class', 'classic', 'classmat',
       'classmate', 'clau', 'claud', 'clay', 'clean', 'clear', 'clerk',
       'clever', 'client', 'clients', 'cliff', 'climb', 'climber',
       'clinic', 'clock', 'clone', 'close', 'closer', 'closest', 'closet',
       'cloth', 'cloud', 'clown', 'club', 'clue', 'clumsi', 'clutch',
       'co', 'coach', 'coal', 'coast', 'coastal', 'cocain', 'cocki',
       'code', 'codi', 'coffe', 'col', 'cold', 'cole', 'colin',
       'collabor', 'collaps', 'collar', 'colleagu', 'collect',
       'collector', 'colleg', 'college', 'collid', 'collin', 'collins',
       'collis', 'colonel', 'coloni', 'color', 'colorado', 'com', 'coma',
       'combat', 'combin', 'come', 'comeback', 'comed', 'comedi',
       'comedian', 'comedy', 'comfort', 'comic', 'comics', 'coming',
       'command', 'commando', 'commerci', 'commiss', 'commission',
       'commit', 'common', 'commun', 'communist', 'community', 'compani',
       'companion', 'company', 'compassion', 'compel', 'compet',
       'competit', 'competition', 'competitor', 'complet', 'complex',
       'complic', 'complicated', 'compos', 'compound', 'compromis',
       'comput', 'computer', 'con', 'conceal', 'conceiv', 'concentr',
       'concept', 'concern', 'concert', 'condemn', 'condit', 'conduct',
       'conductor', 'confeder', 'confess', 'confid', 'confin', 'conflict',
       'confront', 'confus', 'conjur', 'connect', 'connecticut',
       'connection', 'connor', 'conquer', 'consequ', 'consequences',
       'conserv', 'consid'], dtype=object)

In [ ]:
from scipy.spatial.distance import cdist

TopK = 10

query = "a young man who discovers a mysterious secret"

query_binarized_features = vectorizer.transform([query]).toarray()

# Menghitung Jaccard Similarity
similarities = 1 - cdist(
    documents_binarized_features,
    query_binarized_features,
    metric="jaccard"
)

# Mengambil Top 10
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
descriptions = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    descriptions.append(
        str(data.iloc[doc_index]["description"]).replace("\n", " ")
    )
    similarity_scores.append(similarities[doc_index, 0])

results = pd.DataFrame({
    "Title": titles,
    "Description": descriptions,
    "Similarities": similarity_scores
})

display(HTML(results.to_html()))